### ISSUE TITLE
How complete is Windows support?

### ISSUE THREAD

**Issue by elvarb** [BinaryDefense/artillery#13]
From the code there are references to supporting Windows but there are also plenty of references that will not work when using Windows. Compared to the Linux support how comparable is the Windows support?

**Comment by trustedsec** [comment]
Still somewhat in beta - its a manual process as service creations aren't there yet - plan on adding soon.

**Comment by russhaun** [comment]
only commenting because i see this is windows related. Basic support for windows is now there. it has been tested on win 7/8/10 so far.server support to come soon 2008?/2012/2016. would love comments on windows side to see what kind of features you would like to see. check out my repo for ideas already out there feel free to suggest more.
