### ISSUE TITLE
I can't seem to get this to run on windows, please help!

### ISSUE THREAD

**Issue by vonlohmann** [BinaryDefense/artillery#34]
I can't seem to get this to work on windows, because for some reason no matter if I run in powershell or cmd it wont load the different (Y/N) options.
I have attached a file so you can se a bit better what is happening.
It just loads and then instantly exits instead of asking me (Y/N).
I'm new to python, sorry.
![artillery bug](https://cloud.githubusercontent.com/assets/17447391/23836883/924fbe9a-077f-11e7-8246-f506ad2c9a86.png)

**Comment by vonlohmann** [comment]
https://gyazo.com/9d96fb8e2947359c8be2adb52d0b6be4

**Comment by vonlohmann** [comment]
https://gyazo.com/9d96fb8e2947359c8be2adb52d0b6be4

**Comment by vonlohmann** [comment]
![artillery bug 3](https://cloud.githubusercontent.com/assets/17447391/23836917/1b45ed28-0780-11e7-9519-b4a84f0118ca.gif)

**Comment by nultek** [comment]
Are you running on Linux or Windows? You may not have privs to create the required directories. (I just took a quick glance though)

**Comment by vonlohmann** [comment]
I have full permission, and that is what bothers me. For some reason the Windows console and powershell aren't compatible with scripts that require you to input things, like y/n.
At least not when they are coded that way.

**Comment by nultek** [comment]
Can you provide some info about your environment? Windows version, python version, etc?

**Comment by vonlohmann** [comment]
Windows 10

**Comment by russhaun** [comment]
I have just asked for a pull request from my repo for just this. I corrected windows info so now it will install\uninstall and run. works on win 7/8/10, works in python versions from 2.7->3.6 been running this for just me for quite some time. Never released due to not seeing interest.But since i heard that they were working on windows support i decided to fix it properly and request a pull.Still more todo but hopefully they accept it. for now only thing implemented is banning

**Comment by trustedsec** [comment]
Thanks for the PR on that - very awesome stuff, thanks :)
