### ISSUE TITLE
Error with running the script in ubuntu 14.04

### ISSUE THREAD

**Issue by ghadeerd** [BinaryDefense/artillery#39]
When I use python 2.7 to run setup.py I get the error :
File "setup.py", line 11, in <module>
    from src.core import *
  File "/home/ghadeer/artillery/src/core.py", line 40, in <module>
    from src.windows.events import HoneyPotEvent #check events.py for reasoning.
ImportError: No module named windows.events

And with python 3.6 I get the error : 
  File "setup.py", line 11, in <module>
    from src.core import *
  File "/home/ghadeer/artillery/src/core.py", line 40, in <module>
    from src.windows.events import HoneyPotEvent #check events.py for reasoning.
  File "/home/ghadeer/artillery/src/windows/events.py", line 12, in <module>
    import win32api, win32con, win32evtlog, win32evtlogutil, win32security
ModuleNotFoundError: No module named 'win32api'

I also tried to pip install pypiwin32 but also ends with errors : 
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pypiwin32
Storing debug log for failure in /root/.pip/pip.log

**Comment by russhaun** [comment]
I will look into this. think you for telling me.

**Comment by russhaun** [comment]
I have sent you an email with what i found and made appropriate changes. look forward to your response

**Comment by russhaun** [comment]
I don’t know if you got this so I’m posting to GitHub

Hey whats up how are you?

                                I looked into your issue and have a few questions. You state that you have an issue on Ubuntu but yet your problems are related to windows. What is your env setup.? What IDE are you using? Just to let you know this is my setup. In order.

1.win  7pro/ python 2.7.13
2.Win 8.1 pro/python 3.6.1
3.win 10 pro/””                 “”
4. Geany ide
5 .standalone windows sdks
2008/12/16 all to be added incl. HV-core

Software used:

Python: https://www.python.org/downloads/
Pywin32: https://sourceforge.net/projects/pywin32/files/pywin32/ 
Geany: https://www.geany.org/



I tested python 2.7 and reproduced your error. it appears to not find path for events.py. if I move it to src directory it works so simple enough fix.
On python 3.6 I can not reproduce error it all works as it should. The only thing I did notice is the error you describe ModuleNotFoundError: No module named 'win32api' I did get on my win10 machine with VS installed a while back it installs it’s own version of python and breaks everything if you had the original version already installed. Definitely sounds like a path issue. You can tell when you try to install pywin32 look at the path it goes to. If it’s c:\program files then its Microsofts version .The one from python website is installed to user path C:\username\appdata\. For me ripping out VS, and cleaning the registry worked. I didn’t like the way the way it formatted my code. It kept saying that there were errors when I knew it worked. Nuisance. It really screwed my machine had to rebuild it. Not sure if this is your issue just throwing it out there. I will push out the fix for py 2.7. let me know I want to resolve your issue. Also there is no way right now to install pywin32 from pip you must install from website above.
                                                                                                                                                                                                                                                RH

**Comment by russhaun** [comment]
decided to fire this up in kali and now i see your error for python 2.7 On windows the issue is fixed. on linux will have to look into solution. working on it.

**Comment by russhaun** [comment]
just uploaded some changes this is what i get now. Let me know if it works. from top left kali, win 7 on bottom is win10. you will get an error about /etc/init.d/artillery on linux . ignore for now. launch manually from /var/artillery. working out service install details now.
![39](https://user-images.githubusercontent.com/20805369/27929470-2bdbe494-6261-11e7-9fb0-6f35d1318111.png)

**Comment by russhaun** [comment]
Just threw up a copy of ubuntu 14.04 fully up to-date. installed and this is what i got. should work now
![39 ubuntu](https://user-images.githubusercontent.com/20805369/27934056-fc6cd0c2-6271-11e7-947c-9ed23b362745.png)

**Comment by baffoon** [comment]
Line 74 in /var/artillery/artillery.py has a typo.

os.mkdirs("/var/artillery/database/")

Should be os.mkdir("/var/artillery/database/")

Just providing a heads up.

The current issue at hand persists in Ubuntu Server 16.04. I have been fiddling with the code and have found a workaround. Not perfect, but it works. I've provided images.

![poc](https://user-images.githubusercontent.com/17787708/28246042-beee7db8-69d8-11e7-8dc3-dc749dc29a98.PNG)
![ubuntu-16-serv-workaround](https://user-images.githubusercontent.com/17787708/28246046-ce0ad40e-69d8-11e7-9656-e88284b21690.PNG)

**Comment by russhaun** [comment]
My pull request for this issue has not been received yet. Please test from my repo as changes have been applied to resolve this issue and let me know if it works.
