### ISSUE TITLE
Artillery isn't actually compatible with Windows

### ISSUE THREAD

**Issue by GWigWam** [BinaryDefense/artillery#9]
For instance, core.is_already_banned() uses the Linux command 'iptables', this will not work on windows. There are similar things all trough the code. It is clear this program wasn't made for windows.

Consider removing Windows from "Supported platforms" in the readme.

**Comment by trustedsec** [comment]
There is code in there for Windows - service creation testing is almost done. Appreciate the post - but not accurate.

**Comment by russhaun** [comment]
only commenting because i see this is windows related. Basic support for windows is now there. it has been tested on win 7/8/10 so far.server support to come soon 2008?/2012/2016. would love comments on windows side to see what kind of features you would like to see. check out my repo for ideas already out there feel free to suggest more.
